import type { ColumnDef, FolderNode, MetaMap } from './folder';

export type SpItemRef = { listId: string; itemId: string };

export type SpLibraryRef = { listId: string; displayName: string; rootPath: string };

export type GraphImportJson = {
  schemaVersion: 1;
  source: 'graph-ps';
  generatedAt: string;
  siteUrl: string;
  siteId: string;
  tree: FolderNode;
  columns: ColumnDef[];
  meta: Record<string, MetaMap>;
  stats: { libraryCount: number; folderCount: number; fileCount: number };
  spLookup?: Record<string, SpItemRef>;
  libraries?: SpLibraryRef[];
};

export type GraphScriptInputs = {
  tenantId: string;
  clientId: string;
  siteUrl: string;
};

export function generatePowerShellScript({
  tenantId,
  clientId,
  siteUrl,
}: GraphScriptInputs): string {
  const safeTenantId = tenantId.trim();
  const safeClientId = clientId.trim();
  const safeSiteUrl = siteUrl.trim().replace(/\/+$/, '');

  return SCRIPT_TEMPLATE.replace('__TENANT_ID__', safeTenantId)
    .replace('__CLIENT_ID__', safeClientId)
    .replace('__SITE_URL__', safeSiteUrl);
}

export function parseGraphImportJson(text: string): GraphImportJson {
  let parsed: unknown;
  try {
    parsed = JSON.parse(text);
  } catch (err) {
    throw new Error('File is not valid JSON.');
  }
  if (!parsed || typeof parsed !== 'object') {
    throw new Error('JSON root is not an object.');
  }
  const p = parsed as Record<string, unknown>;
  if (p.schemaVersion !== 1) {
    throw new Error(`Unsupported schemaVersion ${String(p.schemaVersion)}; expected 1.`);
  }
  if (p.source !== 'graph-ps') {
    throw new Error(`Unexpected source "${String(p.source)}"; expected "graph-ps".`);
  }
  const tree = p.tree as { kind?: string } | undefined;
  if (!tree || tree.kind !== 'folder') {
    throw new Error('Missing or invalid root tree (must be a folder).');
  }
  if (!Array.isArray(p.columns)) {
    throw new Error('Missing or invalid columns array.');
  }
  if (!p.meta || typeof p.meta !== 'object') {
    throw new Error('Missing or invalid meta object.');
  }
  if (!p.stats || typeof p.stats !== 'object') {
    throw new Error('Missing or invalid stats object.');
  }
  return parsed as GraphImportJson;
}

const SCRIPT_TEMPLATE = String.raw`<#
  Data Magazine — SharePoint import via Microsoft Graph
  Generated by Data Magazine. Run in PowerShell 5.1 or later.

  Authenticates with the device code flow (a browser will open for sign-in),
  then enumerates every document library under the configured SharePoint site
  and writes data-magazine-import.json next to this script.

  No external modules are required.
#>

$ErrorActionPreference = 'Stop'
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

# ----- Configuration (injected from Data Magazine) -----
$TenantId  = '__TENANT_ID__'
$ClientId  = '__CLIENT_ID__'
$SiteUrl   = '__SITE_URL__'
$OutputFile = Join-Path -Path (Split-Path -Parent $PSCommandPath) -ChildPath 'data-magazine-import.json'

if ([string]::IsNullOrWhiteSpace($TenantId) -or [string]::IsNullOrWhiteSpace($ClientId) -or [string]::IsNullOrWhiteSpace($SiteUrl)) {
    throw 'TenantId, ClientId and SiteUrl must all be set. Regenerate this script from Data Magazine.'
}

# ----- Helpers -----
function Get-AccessToken {
    param([string]$TenantId, [string]$ClientId, [string]$Scope)
    $body = @{ client_id = $ClientId; scope = "$Scope offline_access" }
    Write-Host 'Requesting device code...' -ForegroundColor Cyan
    $deviceCode = Invoke-RestMethod -Method Post -Body $body -Uri ("https://login.microsoftonline.com/$TenantId/oauth2/v2.0/devicecode")
    Write-Host ''
    Write-Host $deviceCode.message -ForegroundColor Yellow
    Write-Host ''
    $interval = [int]$deviceCode.interval
    $deadline = (Get-Date).AddSeconds([int]$deviceCode.expires_in)
    while ((Get-Date) -lt $deadline) {
        Start-Sleep -Seconds $interval
        try {
            $tokenUri = "https://login.microsoftonline.com/$TenantId/oauth2/v2.0/token"
            $tokenBody = @{
                grant_type  = 'urn:ietf:params:oauth:grant-type:device_code'
                client_id   = $ClientId
                device_code = $deviceCode.device_code
            }
            $resp = Invoke-RestMethod -Method Post -ErrorAction Stop -Uri $tokenUri -Body $tokenBody
            return $resp.access_token
        } catch {
            $msg = $null
            try { $msg = ($_.ErrorDetails.Message | ConvertFrom-Json) } catch {}
            if ($null -eq $msg) { throw }
            if ($msg.error -eq 'authorization_pending') { continue }
            if ($msg.error -eq 'slow_down') { $interval += 5; continue }
            throw "Authentication failed: $($msg.error) - $($msg.error_description)"
        }
    }
    throw 'Authentication timed out before the device code was approved.'
}

function Invoke-GraphGet {
    param([string]$Url, [string]$Token)
    $headers = @{ Authorization = "Bearer $Token"; Accept = 'application/json' }
    $items = New-Object System.Collections.Generic.List[object]
    $next = $Url
    while ($next) {
        $resp = Invoke-RestMethod -Method Get -Uri $next -Headers $headers
        if ($null -ne $resp.value) {
            foreach ($v in $resp.value) { [void]$items.Add($v) }
            $next = $resp.'@odata.nextLink'
        } else {
            return $resp
        }
    }
    return $items
}

function Resolve-SiteId {
    param([string]$SiteUrl, [string]$Token)
    $uri = [Uri]$SiteUrl
    $serverPath = $uri.AbsolutePath -replace '/$', ''
    if ([string]::IsNullOrEmpty($serverPath)) { $serverPath = '' }
    $graph = "https://graph.microsoft.com/v1.0/sites/$($uri.Host):$serverPath"
    $site = Invoke-RestMethod -Method Get -Uri $graph -Headers @{ Authorization = "Bearer $Token" }
    return $site.id
}

function ConvertTo-ColumnType {
    param([object]$Column)
    if ($Column.text -and $Column.text.allowMultipleLines) { return 'multiline' }
    if ($Column.choice) { return 'choice' }
    if ($Column.dateTime) { return 'date' }
    if ($Column.boolean) { return 'boolean' }
    return 'text'
}

function Get-LibraryTree {
    param([string]$SiteId, [object]$List, [string]$Token)

    $libName  = $List.displayName
    $listId   = $List.id
    $rootPath = "/$libName"

    Write-Host ("  Library: {0}" -f $libName) -ForegroundColor White

    $colsUrl  = "https://graph.microsoft.com/v1.0/sites/$SiteId/lists/$listId/columns"
    $allCols  = Invoke-GraphGet -Url $colsUrl -Token $Token
    $systemPattern = '^(_|ContentType|Modified|Created|Author|Editor|FileLeafRef|FileRef|FileSizeDisplay|FileDirRef|ID|UniqueId|GUID|owshiddenversion|WorkflowVersion|_UIVersion|_UIVersionString|Attachments|_HasCopyDestinations|_CopySource|ContentVersion|_ModerationStatus|_ModerationComments|InstanceID|Order|_Level|_IsCurrentVersion|ItemChildCount|FolderChildCount|AppAuthor|AppEditor|SortBehavior|FileType|HTML_x0020_File_x0020_Type|_SourceUrl|_SharedFileIndex|DocConcurrencyNumber|Combine|RepairDocument|CheckedOutTitle|CheckedOutUserId|IsCheckedoutToLocal|VirusStatus|CheckoutUser|Title)$'
    $customCols = @($allCols | Where-Object {
        -not $_.hidden -and -not $_.readOnly -and $_.name -notmatch $systemPattern
    })

    $itemsUrl = "https://graph.microsoft.com/v1.0/sites/$SiteId/lists/$listId/items?expand=fields,driveItem&top=200"
    $items    = Invoke-GraphGet -Url $itemsUrl -Token $Token
    if ($null -eq $items) { $items = @() }

    Write-Host ("    columns: {0}, items: {1}" -f $customCols.Count, $items.Count)

    $root = [ordered]@{
        kind       = 'folder'
        id         = "lib:$libName"
        name       = $libName
        path       = $rootPath
        modifiedAt = (Get-Date).ToString('o')
        modifiedBy = ''
        children   = New-Object System.Collections.Generic.List[object]
    }
    $folderMap = @{ $rootPath = $root }
    $meta = @{}
    $spLookup = @{}
    $fileCount = 0
    $folderCount = 0

    foreach ($item in $items) {
        $di = $item.driveItem
        if ($null -eq $di) { continue }
        $name = $di.name
        if ([string]::IsNullOrEmpty($name)) { continue }

        $parentPath = ''
        if ($di.parentReference -and $di.parentReference.path) {
            $parentPath = $di.parentReference.path -replace '^/drives/[^/]+/root:', ''
        }
        $segments = $parentPath -split '/' | Where-Object { $_ -ne '' }

        $parent = $root
        $cumPath = $rootPath
        foreach ($seg in $segments) {
            $cumPath = "$cumPath/$seg"
            if (-not $folderMap.ContainsKey($cumPath)) {
                $f = [ordered]@{
                    kind       = 'folder'
                    id         = "f:$cumPath"
                    name       = $seg
                    path       = $cumPath
                    modifiedAt = ''
                    modifiedBy = ''
                    children   = New-Object System.Collections.Generic.List[object]
                }
                $folderMap[$cumPath] = $f
                [void]$parent.children.Add($f)
                $folderCount++
            }
            $parent = $folderMap[$cumPath]
        }

        $itemPath = "$($parent.path)/$name"
        $modAt = if ($di.lastModifiedDateTime) { [string]$di.lastModifiedDateTime } else { '' }
        $modBy = ''
        if ($di.lastModifiedBy -and $di.lastModifiedBy.user -and $di.lastModifiedBy.user.displayName) {
            $modBy = $di.lastModifiedBy.user.displayName
        }

        if ($di.folder) {
            if (-not $folderMap.ContainsKey($itemPath)) {
                $f = [ordered]@{
                    kind       = 'folder'
                    id         = "f:$itemPath"
                    name       = $name
                    path       = $itemPath
                    modifiedAt = $modAt
                    modifiedBy = $modBy
                    children   = New-Object System.Collections.Generic.List[object]
                }
                $folderMap[$itemPath] = $f
                [void]$parent.children.Add($f)
                $folderCount++
            }
        } else {
            $size = if ($null -ne $di.size) { [long]$di.size } else { 0 }
            $fileNode = [ordered]@{
                kind       = 'file'
                id         = "i:$itemPath"
                name       = $name
                path       = $itemPath
                size       = $size
                modifiedAt = $modAt
                modifiedBy = $modBy
            }
            [void]$parent.children.Add($fileNode)
            $fileCount++

            $spLookup[$itemPath] = @{ listId = $listId; itemId = $item.id }

            $metaMap = @{}
            foreach ($col in $customCols) {
                $val = $item.fields.PSObject.Properties[$col.name]
                if ($null -ne $val) {
                    $vv = $val.Value
                    if ($null -ne $vv -and "$vv" -ne '') {
                        $metaMap[$col.name] = $vv
                    }
                }
            }
            if ($metaMap.Count -gt 0) { $meta[$itemPath] = $metaMap }
        }
    }

    $columnDefs = foreach ($c in $customCols) {
        $def = [ordered]@{
            id    = $c.name
            label = $c.displayName
            type  = (ConvertTo-ColumnType -Column $c)
        }
        if ($c.required) { $def.required = $true }
        if ($c.choice -and $c.choice.choices) { $def.choices = @($c.choice.choices) }
        $def
    }

    return @{
        root        = $root
        columns     = @($columnDefs)
        meta        = $meta
        spLookup    = $spLookup
        listId      = $listId
        rootPath    = $rootPath
        displayName = $libName
        fileCount   = $fileCount
        folderCount = $folderCount
    }
}

# ----- Main -----
Write-Host 'Data Magazine -- SharePoint import via Microsoft Graph' -ForegroundColor Magenta
Write-Host ("Site: {0}" -f $SiteUrl)
Write-Host ''

$token  = Get-AccessToken -TenantId $TenantId -ClientId $ClientId -Scope 'https://graph.microsoft.com/Sites.Read.All'
Write-Host 'Authenticated. Resolving site...'

$siteId = Resolve-SiteId -SiteUrl $SiteUrl -Token $token
Write-Host ("Site resolved: {0}" -f $siteId)
Write-Host 'Enumerating document libraries...'

$lists = Invoke-GraphGet -Url ("https://graph.microsoft.com/v1.0/sites/$siteId/lists?expand=list&top=100") -Token $token
$docLibs = @($lists | Where-Object { $_.list -and $_.list.template -eq 'documentLibrary' -and -not $_.list.hidden })

Write-Host ("Found {0} document libraries." -f $docLibs.Count)
Write-Host ''

$libraries = New-Object System.Collections.Generic.List[object]
foreach ($lib in $docLibs) {
    [void]$libraries.Add((Get-LibraryTree -SiteId $siteId -List $lib -Token $token))
}

if ($libraries.Count -eq 1) {
    $rootTree = $libraries[0].root
} else {
    $children = New-Object System.Collections.Generic.List[object]
    foreach ($l in $libraries) { [void]$children.Add($l.root) }
    $rootTree = [ordered]@{
        kind       = 'folder'
        id         = 'root:imports'
        name       = 'SharePoint imports'
        path       = '/imports'
        modifiedAt = (Get-Date).ToString('o')
        modifiedBy = ''
        children   = $children
    }
}

$columnMap = [ordered]@{}
foreach ($l in $libraries) {
    foreach ($col in $l.columns) {
        if (-not $columnMap.Contains($col.id)) { $columnMap[$col.id] = $col }
    }
}
$combinedColumns = @($columnMap.Values)

$combinedMeta = @{}
foreach ($l in $libraries) {
    foreach ($k in $l.meta.Keys) { $combinedMeta[$k] = $l.meta[$k] }
}

$combinedLookup = @{}
foreach ($l in $libraries) {
    foreach ($k in $l.spLookup.Keys) { $combinedLookup[$k] = $l.spLookup[$k] }
}

$libraryRefs = foreach ($l in $libraries) {
    [ordered]@{
        listId      = $l.listId
        displayName = $l.displayName
        rootPath    = $l.rootPath
    }
}

$totalFolders = ($libraries | ForEach-Object { $_.folderCount } | Measure-Object -Sum).Sum
$totalFiles   = ($libraries | ForEach-Object { $_.fileCount }   | Measure-Object -Sum).Sum

$output = [ordered]@{
    schemaVersion = 1
    source        = 'graph-ps'
    generatedAt   = (Get-Date).ToString('o')
    siteUrl       = $SiteUrl
    siteId        = $siteId
    tree          = $rootTree
    columns       = $combinedColumns
    meta          = $combinedMeta
    spLookup      = $combinedLookup
    libraries     = @($libraryRefs)
    stats         = @{
        libraryCount = $libraries.Count
        folderCount  = if ($null -eq $totalFolders) { 0 } else { [int]$totalFolders }
        fileCount    = if ($null -eq $totalFiles)   { 0 } else { [int]$totalFiles }
    }
}

$json = $output | ConvertTo-Json -Depth 64
[System.IO.File]::WriteAllText($OutputFile, $json, [System.Text.UTF8Encoding]::new($false))

Write-Host ''
Write-Host ("Done. Wrote {0}" -f $OutputFile) -ForegroundColor Green
Write-Host ("  Libraries: {0}" -f $output.stats.libraryCount)
Write-Host ("  Folders:   {0}" -f $output.stats.folderCount)
Write-Host ("  Files:     {0}" -f $output.stats.fileCount)
Write-Host ''
Write-Host "In Data Magazine, go to Settings -> SharePoint via Microsoft Graph -> 'Import JSON output' and select this file."
`;
