import type { Diff } from './sharepointDiff';
import type { SpItemRef, SpLibraryRef } from './graphImportScript';

export type WriteBackInputs = {
  tenantId: string;
  clientId: string;
  siteUrl: string;
  diff: Diff;
  spLookup: Record<string, SpItemRef>;
  libraries: SpLibraryRef[];
};

export type WriteBackPreparation = {
  script: string;
  mappedItemCount: number;
  unmappedItemCount: number;
  unmappedPaths: string[];
};

export function prepareWriteBack({
  tenantId,
  clientId,
  siteUrl,
  diff,
  spLookup,
  libraries,
}: WriteBackInputs): WriteBackPreparation {
  const enriched: EnrichedChange[] = [];
  const unmappedPaths: string[] = [];

  for (const item of diff.changedItems) {
    const sp = spLookup[item.path];
    if (!sp) {
      unmappedPaths.push(item.path);
      continue;
    }
    enriched.push({
      path: item.path,
      fileName: item.fileName,
      spListId: sp.listId,
      spItemId: sp.itemId,
      changes: item.changes.map((c) => ({
        columnId: c.columnId,
        after: c.after ?? null,
      })),
    });
  }

  const payload = {
    addedColumns: diff.addedColumns,
    changedItems: enriched,
    libraries,
  };

  const jsonText = JSON.stringify(payload, null, 2);

  const script = WRITE_BACK_TEMPLATE
    .replace('__TENANT_ID__', tenantId.trim())
    .replace('__CLIENT_ID__', clientId.trim())
    .replace('__SITE_URL__', siteUrl.trim().replace(/\/+$/, ''))
    .replace('__WRITE_BACK_JSON__', jsonText);

  return {
    script,
    mappedItemCount: enriched.length,
    unmappedItemCount: unmappedPaths.length,
    unmappedPaths,
  };
}

type EnrichedChange = {
  path: string;
  fileName: string;
  spListId: string;
  spItemId: string;
  changes: { columnId: string; after: unknown }[];
};

const WRITE_BACK_TEMPLATE = String.raw`<#
  Data Magazine — SharePoint write-back via Microsoft Graph
  Generated by Data Magazine. Run in PowerShell 5.1 or later.

  Authenticates with the device code flow, then:
    1. POSTs each newly added column to every document library under the site
       (those captured in your last import).
    2. PATCHes each changed list item's fields with the new values.

  No external modules are required. Sites.ReadWrite.All delegated permission
  on the Entra ID app is required.
#>

$ErrorActionPreference = 'Stop'
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

# ----- Configuration (injected from Data Magazine) -----
$TenantId = '__TENANT_ID__'
$ClientId = '__CLIENT_ID__'
$SiteUrl  = '__SITE_URL__'

# ----- Embedded write-back payload (also injected) -----
$WriteBackJson = @'
__WRITE_BACK_JSON__
'@

if ([string]::IsNullOrWhiteSpace($TenantId) -or [string]::IsNullOrWhiteSpace($ClientId) -or [string]::IsNullOrWhiteSpace($SiteUrl)) {
    throw 'TenantId, ClientId and SiteUrl must all be set. Regenerate this script from Data Magazine.'
}

$data = $WriteBackJson | ConvertFrom-Json

# ----- Helpers -----
function Get-AccessToken {
    param([string]$TenantId, [string]$ClientId, [string]$Scope)
    $body = @{ client_id = $ClientId; scope = "$Scope offline_access" }
    Write-Host 'Requesting device code...' -ForegroundColor Cyan
    $deviceCode = Invoke-RestMethod -Method Post -Body $body -Uri ("https://login.microsoftonline.com/$TenantId/oauth2/v2.0/devicecode")
    Write-Host ''
    Write-Host $deviceCode.message -ForegroundColor Yellow
    Write-Host ''
    $interval = [int]$deviceCode.interval
    $deadline = (Get-Date).AddSeconds([int]$deviceCode.expires_in)
    while ((Get-Date) -lt $deadline) {
        Start-Sleep -Seconds $interval
        try {
            $tokenUri = "https://login.microsoftonline.com/$TenantId/oauth2/v2.0/token"
            $tokenBody = @{
                grant_type  = 'urn:ietf:params:oauth:grant-type:device_code'
                client_id   = $ClientId
                device_code = $deviceCode.device_code
            }
            $resp = Invoke-RestMethod -Method Post -ErrorAction Stop -Uri $tokenUri -Body $tokenBody
            return $resp.access_token
        } catch {
            $msg = $null
            try { $msg = ($_.ErrorDetails.Message | ConvertFrom-Json) } catch {}
            if ($null -eq $msg) { throw }
            if ($msg.error -eq 'authorization_pending') { continue }
            if ($msg.error -eq 'slow_down') { $interval += 5; continue }
            throw "Authentication failed: $($msg.error) - $($msg.error_description)"
        }
    }
    throw 'Authentication timed out before the device code was approved.'
}

function Resolve-SiteId {
    param([string]$SiteUrl, [string]$Token)
    $uri = [Uri]$SiteUrl
    $serverPath = $uri.AbsolutePath -replace '/$', ''
    if ([string]::IsNullOrEmpty($serverPath)) { $serverPath = '' }
    $graph = "https://graph.microsoft.com/v1.0/sites/$($uri.Host):$serverPath"
    $site = Invoke-RestMethod -Method Get -Uri $graph -Headers @{ Authorization = "Bearer $Token" }
    return $site.id
}

function Build-ColumnPayload {
    param([object]$Col)
    $payload = [ordered]@{
        name        = $Col.id
        displayName = $Col.label
    }
    if ($Col.required) { $payload.required = $true }
    switch ($Col.type) {
        'text'      { $payload.text     = @{ allowMultipleLines = $false; appendChangesToExistingText = $false; maxLength = 255 } }
        'multiline' { $payload.text     = @{ allowMultipleLines = $true;  appendChangesToExistingText = $false } }
        'choice'    {
            $choices = @()
            if ($Col.choices) { $choices = @($Col.choices) }
            $payload.choice = @{ choices = $choices; displayAs = 'dropDownMenu' }
        }
        'date'      { $payload.dateTime = @{ format = 'dateTime' } }
        'boolean'   { $payload.boolean  = @{} }
        default     { $payload.text     = @{ allowMultipleLines = $false } }
    }
    return $payload
}

function Get-ErrorMessage {
    param([object]$Err)
    $msg = $Err.Exception.Message
    try {
        $parsed = $Err.ErrorDetails.Message | ConvertFrom-Json
        if ($parsed.error.message) { return $parsed.error.message }
    } catch {}
    return $msg
}

# ----- Main -----
Write-Host 'Data Magazine -- SharePoint write-back via Microsoft Graph' -ForegroundColor Magenta
Write-Host ("Site: {0}" -f $SiteUrl)
Write-Host ("New columns: {0}" -f @($data.addedColumns).Count)
Write-Host ("Items to update: {0}" -f @($data.changedItems).Count)
Write-Host ''

$token  = Get-AccessToken -TenantId $TenantId -ClientId $ClientId -Scope 'https://graph.microsoft.com/Sites.ReadWrite.All'
Write-Host 'Authenticated. Resolving site...'

$siteId = Resolve-SiteId -SiteUrl $SiteUrl -Token $token
Write-Host ("Site resolved: {0}" -f $siteId)
Write-Host ''

$jsonHeaders = @{
    Authorization  = "Bearer $token"
    'Content-Type' = 'application/json'
    Accept         = 'application/json'
}

# === 1. Add new columns to each library ===
$columnSuccess = 0
$columnFail = 0
if (@($data.addedColumns).Count -gt 0 -and @($data.libraries).Count -gt 0) {
    Write-Host 'Adding new columns to libraries...' -ForegroundColor Cyan
    foreach ($lib in $data.libraries) {
        foreach ($col in $data.addedColumns) {
            $payload = Build-ColumnPayload -Col $col
            $body = $payload | ConvertTo-Json -Depth 10 -Compress:$false
            $url = "https://graph.microsoft.com/v1.0/sites/$siteId/lists/$($lib.listId)/columns"
            try {
                Invoke-RestMethod -Method Post -Uri $url -Body $body -Headers $jsonHeaders | Out-Null
                $columnSuccess++
                Write-Host ("  + {0} -> {1}" -f $col.id, $lib.displayName) -ForegroundColor Green
            } catch {
                $columnFail++
                $errMsg = Get-ErrorMessage -Err $_
                Write-Host ("  ! {0} -> {1}: {2}" -f $col.id, $lib.displayName, $errMsg) -ForegroundColor Red
            }
        }
    }
    Write-Host ''
}

# === 2. PATCH items ===
$itemSuccess = 0
$itemFail = 0
if (@($data.changedItems).Count -gt 0) {
    Write-Host 'Updating list items...' -ForegroundColor Cyan
    foreach ($item in $data.changedItems) {
        $fieldsPayload = [ordered]@{}
        foreach ($ch in $item.changes) {
            $val = $ch.after
            if ("$val" -eq '') { $val = $null }
            $fieldsPayload[$ch.columnId] = $val
        }
        $body = $fieldsPayload | ConvertTo-Json -Depth 10 -Compress:$false
        $url = "https://graph.microsoft.com/v1.0/sites/$siteId/lists/$($item.spListId)/items/$($item.spItemId)/fields"
        try {
            Invoke-RestMethod -Method Patch -Uri $url -Body $body -Headers $jsonHeaders | Out-Null
            $itemSuccess++
            Write-Host ("  ~ {0}" -f $item.path) -ForegroundColor Cyan
        } catch {
            $itemFail++
            $errMsg = Get-ErrorMessage -Err $_
            Write-Host ("  ! {0}: {1}" -f $item.path, $errMsg) -ForegroundColor Red
        }
    }
    Write-Host ''
}

# === Summary ===
Write-Host 'Done.' -ForegroundColor Green
Write-Host ("  Columns added:  {0} (failed: {1})" -f $columnSuccess, $columnFail)
Write-Host ("  Items updated:  {0} (failed: {1})" -f $itemSuccess, $itemFail)
if ($columnFail -gt 0 -or $itemFail -gt 0) {
    Write-Host ''
    Write-Host 'One or more operations failed. Re-run Data Magazine and re-import the site to refresh the SharePoint IDs, then try again.' -ForegroundColor Yellow
}
`;
